### ISSUE TITLE
Art Requests (open to all)

### ISSUE THREAD

**Issue by andreaabellera** [andreaabellera/Casually-CSS#1]
Please submit art requests by commenting in this thread

**Comment by Marshmallows7920** [comment]
An unrestrained cavegirl

**Comment by Marshmallows7920** [comment]
a panda

**Comment by Marshmallows7920** [comment]
a vaquita

**Comment by Marshmallows7920** [comment]
a turtle

**Comment by Marshmallows7920** [comment]
Dugong

**Comment by andreaabellera** [comment]
@Marshmallows7920 
I made you a vaquita! It looks strangely like something else though
https://andreaabellera.github.io/Casually-CSS/#beluga

**Comment by andreaabellera** [comment]
@Marshmallows7920 
I kid, here's a dugong
https://andreaabellera.github.io/Casually-CSS/#dugong

**Comment by misaasper** [comment]
I bless this project

**Comment by andreaabellera** [comment]
Thank you AsperMISA!!

**Comment by Marshmallows7920** [comment]
Andrea why are you talking to yourself 👀💀

**Comment by mahyarmirrashed** [comment]
IEEE Logo with side arrow spinning around: https://res.cloudinary.com/crunchbase-production/image/upload/c_lpad,f_auto,q_auto:eco,dpr_1/bsmq8rbdsnijtp9hbtg5
